#!/usr/bin/env sh

# Needed environment variables:
# VIDEO_ID: The YouTube video id to target
# AWS_ACCESS_KEY_ID: AWS Access Key
# AWS_SECRET_ACCESS_KEY: AWS Secret Access Key

# TODO:
#   Stop if thumbnails already in S3

# Work in /tmp/{VIDEO_ID}
cd /tmp
mkdir -p "talksearch/$VIDEO_ID"
cd "./talksearch/$VIDEO_ID"

# Download the video
youtube-dl \
  --output "video.mp4" \
  --format 133 \
  --continue \
  "$VIDEO_ID"

# Extract one thumbnail for every minute of video
ffmpeg \
  -i "video.mp4" \
  -vf fps=1/60 \
  "%d.jpg"

# Push thumbnails to S3
aws s3 \
  cp . \
  "s3://talksearch/thumbnails/${VIDEO_ID}/" \
  --recursive \
  --include "*.jpg"
# video_id="$1"
# bucket_name="pixelastic-talksearch"
# path_tmp="/tmp/talksearch"
# path_destination="${path_tmp}/${video_id}"



## Push all thumbnails to S3, under the videoId directory

