#!/usr/bin/env sh
set -e

IMAGE_NAME="talksearch"
CONTAINER_NAME="talksearch"
VIDEO_ID=$1

mkdir -p /tmp/docker

# Create image
echo "CREATE IMAGE"
docker build -t $IMAGE_NAME .

# Delete previous container
echo "DELETE CONTAINER"
docker rm --force $CONTAINER_NAME

# Run container
echo "RUN CONTAINER"
docker run \
  --name $CONTAINER_NAME \
  -v /tmp/docker:/tmp \
  -e TALKSEARCH_MODE='dev' \
  -e VIDEO_ID="$VIDEO_ID" \
  $IMAGE_NAME
