#!/usr/bin/env sh
# --no-watchman is needed otherwise Jest got confused as to which file changed
# and run tests for the wrong files
jest \
  --config ./jest.config.js \
  --watch \
  --no-watchman \
  ./src ./configs
